# .github/workflows/keep-alive.yml

name: Keep Render API Warm

on:
  schedule:
    # Runs every 15 minutes
    # The cron string '*/15 * * * *' means:
    # */15: every 15th minute (0, 15, 30, 45)
    # *: every hour
    # *: every day of the month
    # *: every month
    # *: every day of the week
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  ping:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: Checkout repository (optional, but good practice)
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Ping Render API Health Endpoint
        run: |
          # Retrieve the API URL from GitHub Secrets
          API_URL="${{ secrets.RENDER_API_HEALTH_URL }}"

          echo "Attempting to ping: $API_URL"

          # Use curl to send a GET request
          # -s: silent (don't show progress)
          # -o /dev/null: discard output (don't save response body)
          # -w "%{http_code}": print only the HTTP status code
          response_code=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL" )

          echo "Received HTTP Status Code: $response_code"

          # Check if the response was 200 OK
          if [ "$response_code" -ne 200 ]; then
            echo "Error: API did not return 200 OK. Status: $response_code"
            exit 1 # Fail the job if the API is not healthy
          else
            echo "API is healthy (200 OK)."
          fi
        env:
          # This line links the secret to an environment variable within the job
          RENDER_API_HEALTH_URL: ${{ secrets.RENDER_API_HEALTH_URL }}
